<?php
    $lang = array(
        //header
        "title"   => "无敌超市",
        "email"   => "邮箱",
        "phone"   => "联系方式",
        "home"    => "主页",
        "shop"    => "商店",
        "review"  => "感言",
        "more"    => "更多",
        "news"    => "新闻",
        "contact" => "联系我们",
        "about"   => "关于我们",
        "eng"     => "英语",
        "man"     => "华语",
        "save"    => "保存",
        "login/re"=> "登录 / 注册",
        "chglg"   => "语言",
        "cart"    => "购物车",
        "checkout"=> "结账",
        //footer
        "slogan1" => "我们为您准备的都是",
        "slogan2" => "品质保证的货物。",
        "fcontact"=> "联系我们",
        "links"   => "链接",
        "top"     => "人气",
        "shopping"=> "商店",
        "fabout"  => "关于我们",
        "fcontact"=> "联系我们",
        "help"    => "帮助",
        "explore" => "探索",
        "new_prod"=> "最新产品",
        "account" => "会员中心",
        "support" => "求助",
        "faq"     => "常温问题",
        "cpyright"=> "版权所有",
        "login"   => "登录",
        "cred"    => "请填写您的资料以登录。",
        "password"=> "密码",
        "seepwd"  => "显示密码",
        "fgtpwd"  => "忘记密码?",
        "no_acc"  => "第一次来这里？ 立刻创建新账户吧。",
        "register"=> "创建账户",
        //register
        "signup"  => "注册",
        "fillform"=> "请填写此表格以创建一个帐户。",
        "fname"   => "名字",
        "lname"   => "姓氏",
        "cfmpwd"  => "确认密码",
        "submit"  => "提交",
        "reset"   => "重置",
        "have_acc"=> "已有账户？",
        "backtolg"=> "马上登录",
        //profile layouts
        "dboard"  => "会员中心",
        "order"   => "订单记录",
        "payment" => "付款方式",
        "address" => "地址",
        "accountd"=> "详细资料",
        "pwd_chg" => "修改密码",
        "logout"  => "注销登入",
        //profile
        "p1"      => "您好,(如果不是",
        "p2"      => "请",
        "p3"      => "注销登入",
        "p4"      => "在您的会员中心。您可以轻松查看和查看您最近的订单、管理您的送货地址和账单地址以及编辑您的密码和帐户详细信息。",
        //forgetpass
        "resetpwd"=> "重置密码",
        "p5"      => "请输入您的电子邮件以接收密码重置代码",
        "p6"      => "输入你的电子邮箱",
        "send"    => "发送",
        //vieworder
        "rid"     => "收据号码",
        "rname"   => "收件人姓名",
        "tdate"   => "交易日期",
        "total"   => "总额 (RM)",
        "status"  => "状态",
        "action"  => "更多"
    );
?>