<?php
    $lang = array(
        //header
        "title"   => "TheGrabGroceries",
        "email"   => "E-mail",
        "phone"   => "Phone",
        "home"    => "Home",
        "shop"    => "Shop",
        "review"  => "Testimonial",
        "more"    => "More",
        "news"    => "News",
        "contact" => "Contact Us",
        "about"  => "About Us",
        "eng"     => "English",
        "man"     => "Chinese",
        "save"    => "Save",
        "login/re"=> "Login / Register",
        "chglg"   => "Language",
        "cart"    => "Cart",
        "checkout"=> "Checkout",
        //footer
        "slogan1" => "We are here to provide you",
        "slogan2" => "with just the greatest stuff.",
        "fcontact"=> "Contact Us",
        "links"   => "Links",
        "top"     => "Top Sellers",
        "shopping"=> "Shopping",
        "fabout"  => "About Us",
        "fcontact"=> "Contact Us",
        "help"    => "Help",
        "explore" => "Explore",
        "new_prod"=> "New Product",
        "account" => "My Account",
        "support" => "Support",
        "faq"     => "FAQs",
        "cpyright"=> "Copyright",
        //login
        "login"   => "Login to",
        "cred"    => "Please fill in your credentials to login.",
        "password"=> "Password",
        "seepwd"  => "Show Password",
        "fgtpwd"  => "Forget Password?",
        "no_acc"  => "Don't have an account?",
        "register"=> "Sign Up Now",
        //register
        "signup"  => "Sign Up",
        "fillform"=> "Please fill this form to create an account.",
        "fname"   => "First Name",
        "lname"   => "Last Name",
        "cfmpwd"  => "Confirm Password",
        "submit"  => "Submit",
        "reset"   => "Reset",
        "have_acc"=> "Already have an account?",
        "backtolg"=> "Login here",
        //profile layouts
        "dboard"  => "Dashboard",
        "order"   => "Order",
        "payment" => "Payment Method",
        "address" => "Address",
        "accountd"=> "Account Details",
        "pwd_chg" => "Password Changes",
        "logout"  => "Logout",
        //profile
        "p1"      => "Hello,(If not",
        "p2"      => "please",
        "p3"      => "Logout",
        "p4"      => "From your account dashboard. you can easily check & view your recent orders, manage your shipping and billing addresses and edit your password and account details.",
        //forgetpass
        "resetpwd"=> "Reset Password",
        "p5"      => "Please enter your email to receive password reset PIN",
        "p6"      => "Enter your e-mail",
        "send"    => "Send",
        //vieworder
        "rid"     => "Receipt ID",
        "rname"   => "Receipt Name",
        "tdate"   => "Transaction Date",
        "total"   => "Total (RM)",
        "status"  => "Status",
        "action"  => "Action"
    ); 
?>